// Static seed data for the Foundators prototype.
// In a real product this would come from a database / API; here it seeds the
// Zustand store on first load so the app has realistic content out of the box.

export const KABIR = {
  key: 'kabir',
  uniqueId: 'FD001',
  name: 'Kabir Anand',
  handle: '@kabiranand',
  avatar: 'https://i.pravatar.cc/160?img=13',
  role: 'Founder · Building Foundators',
  bio: "Building products that connect ideas with the people who can make them real. Currently heads-down on my next venture. Based in India, shipping for the world.",
  followers: '1.8K',
  following: '312',
  posts: '24',
  verified: true,
  skills: ['Product', 'Startups', 'Design', 'Strategy'],
  location: 'Bangalore, India',
  builderScore: { score: 8.7, projects: 6, collaborations: 14, skillsVerified: 4, contribution: 'High', referrals: 3 },
};

export const USERS = {
  arjun: {
    key: 'arjun',
    uniqueId: 'FD002',
    name: 'Arjun Verma',
    handle: '@arjunverma',
    avatar: 'https://i.pravatar.cc/160?img=12',
    role: 'AI Builder & Indie Founder · EdTech.ai',
    bio: "Building an AI tutor that adapts to how every student actually learns. Ex-Byju's, now heads-down on Learnova AI.",
    followers: '12.4K',
    following: '482',
    posts: '86',
    verified: true,
    skills: ['AI', 'Development', 'EdTech', 'Product'],
    location: 'Bangalore, India',
    builderScore: { score: 9.4, projects: 12, collaborations: 24, skillsVerified: 8, contribution: 'High', referrals: 7 },
  },
  meera: {
    key: 'meera',
    uniqueId: 'FD003',
    name: 'Meera Kapoor',
    handle: '@meerakapoor',
    avatar: 'https://i.pravatar.cc/160?img=44',
    role: 'HealthTech Founder & Product Builder · HealthSync',
    bio: 'Founder of HealthSync. Making preventive care accessible for tier-2 and tier-3 India.',
    followers: '9.8K',
    following: '310',
    posts: '54',
    verified: true,
    skills: ['HealthTech', 'Product', 'Startups', 'Operations'],
    location: 'Mumbai, India',
    builderScore: { score: 9.1, projects: 9, collaborations: 19, skillsVerified: 6, contribution: 'High', referrals: 5 },
  },
  rohan: {
    key: 'rohan',
    uniqueId: 'FD004',
    name: 'Rohan Singh',
    handle: '@rohansingh',
    avatar: 'https://i.pravatar.cc/160?img=15',
    role: 'Building in SaaS & AI · FitTrack',
    bio: 'Building FitTrack — a fitness platform that actually understands you. Looking for a co-founder to build this with.',
    followers: '15.6K',
    following: '201',
    posts: '112',
    verified: false,
    skills: ['SaaS', 'AI', 'Fitness', 'Startups'],
    location: 'Delhi, India',
    builderScore: { score: 8.2, projects: 14, collaborations: 11, skillsVerified: 5, contribution: 'Medium', referrals: 4 },
  },
  ishita: {
    key: 'ishita',
    uniqueId: 'FD005',
    name: 'Ishita Rao',
    handle: '@ishr_rao',
    avatar: 'https://i.pravatar.cc/160?img=48',
    role: 'Design Engineer & Maker',
    bio: 'Product design engineer. I make interfaces that feel inevitable.',
    followers: '7.2K',
    following: '145',
    posts: '38',
    verified: true,
    skills: ['Design', 'Product', 'Development'],
    location: 'Pune, India',
    builderScore: { score: 8.9, projects: 7, collaborations: 21, skillsVerified: 7, contribution: 'High', referrals: 6 },
  },
  sophia: {
    key: 'sophia',
    uniqueId: 'FD006',
    name: 'Sophia Turner',
    handle: '@sophiaturner',
    avatar: 'https://i.pravatar.cc/160?img=47',
    role: 'Investor & Community Builder',
    bio: 'Early-stage investor. I DM founders I believe in.',
    followers: '22K',
    following: '89',
    posts: '21',
    verified: true,
    skills: ['Investing', 'Strategy', 'Fundraising'],
    location: 'San Francisco, US',
    builderScore: { score: 9.6, projects: 3, collaborations: 32, skillsVerified: 4, contribution: 'High', referrals: 15 },
  },
  daniel: {
    key: 'daniel',
    uniqueId: 'FD007',
    name: 'Daniel Brooks',
    handle: '@danielbrooks',
    avatar: 'https://i.pravatar.cc/160?img=52',
    role: 'Full-stack Engineer',
    bio: 'Full-stack engineer, open to collaborating on interesting problems.',
    followers: '3.1K',
    following: '560',
    posts: '12',
    verified: false,
    skills: ['Development', 'AI', 'SaaS'],
    location: 'Bangalore, India',
    builderScore: { score: 7.5, projects: 4, collaborations: 8, skillsVerified: 3, contribution: 'Medium', referrals: 1 },
  },
  emily: {
    key: 'emily',
    uniqueId: 'FD008',
    name: 'Emily Carter',
    handle: '@emilycarter',
    avatar: 'https://i.pravatar.cc/160?img=45',
    role: 'Growth & Marketing',
    bio: 'Growth marketer for early-stage startups.',
    followers: '5.4K',
    following: '320',
    posts: '19',
    verified: false,
    skills: ['Marketing', 'Growth', 'Startups'],
    location: 'Mumbai, India',
    builderScore: { score: 7.9, projects: 5, collaborations: 10, skillsVerified: 3, contribution: 'Medium', referrals: 2 },
  },
  james: {
    key: 'james',
    uniqueId: 'FD009',
    name: 'James Wilson',
    handle: '@jameswilson',
    avatar: 'https://i.pravatar.cc/160?img=14',
    role: 'Product Manager',
    bio: 'PM by day, indie hacker by night.',
    followers: '4.2K',
    following: '275',
    posts: '27',
    verified: false,
    skills: ['Product', 'Strategy', 'Operations'],
    location: 'Hyderabad, India',
    builderScore: { score: 8.0, projects: 6, collaborations: 9, skillsVerified: 4, contribution: 'Medium', referrals: 2 },
  },
};

export const STARTUPS = {
  learnova: {
    key: 'learnova',
    name: 'Learnova AI',
    logoBg: 'linear-gradient(135deg,#8a5cff,#3b1f8f)',
    logoText: 'L',
    tag: 'AI',
    tagBg: 'rgba(217,172,61,0.15)',
    tagColor: '#f7dd8f',
    desc: 'Personalized AI tutor for every student. Learnova adapts pacing, explanations, and practice sets to how each student actually learns.',
    stage: 'MVP',
    category: 'EdTech',
    location: 'Bangalore, India',
    followers: '3.2K',
  },
  greenmetric: {
    key: 'greenmetric',
    name: 'Greenmetric',
    logoBg: 'linear-gradient(135deg,#1f6b3f,#0b2f1c)',
    logoText: '🌿',
    tag: 'ClimateTech',
    tagBg: 'rgba(46,204,113,0.15)',
    tagColor: '#2ecc71',
    desc: 'Helping industries measure & reduce their carbon footprint with real-time emissions tracking.',
    stage: 'Seed',
    category: 'Climate',
    location: 'San Francisco, US',
    followers: '2.7K',
  },
  payvance: {
    key: 'payvance',
    name: 'Payvance',
    logoBg: '#111111',
    logoBorder: '1px solid rgba(212,175,55,0.22)',
    logoText: 'P',
    tag: 'FinTech',
    tagBg: 'rgba(91,141,255,0.15)',
    tagColor: '#5b8dff',
    desc: 'Modern payment infrastructure for high-growth businesses — built for speed and reliability at scale.',
    stage: 'Series A',
    category: 'FinTech',
    location: 'Mumbai, India',
    followers: '4.8K',
  },
};

// Posts are the single source of truth for the feed, profile tabs, and comment
// counts. `authorKey` is either a USERS key or 'kabir'.
export const INITIAL_POSTS = [
  {
    id: 'arjun_idea',
    authorKey: 'arjun',
    tagType: 'idea',
    text: "An AI tutor that adapts to every student's learning style.",
    meta: 'Founder · EdTech.ai · 2h ago',
    cats: ['ai'],
    media: 'brain',
    cats2: ['Education', 'AI'],
    likes: 128,
    shares: 21,
  },
  {
    id: 'meera_update',
    authorKey: 'meera',
    tagType: 'update',
    text: 'Just launched our beta today! 🎉 247 early users in 72 hours.',
    meta: 'Founder · HealthSync · 5h ago',
    cats: ['healthtech'],
    stat: { label: 'Early Users', value: '247', delta: '↑ 247% vs last 72h' },
    likes: 203,
    shares: 17,
    likedDefault: true,
  },
  {
    id: 'rohan_cofounder',
    authorKey: 'rohan',
    tagType: 'cofounder',
    text: 'Building a fitness tracking platform that actually understands you.',
    meta: 'Founder · FitTrack · 1d ago',
    cats: ['indie', 'cofounder'],
    looking: ['Full-stack Dev', 'UI/UX Designer', 'Growth Marketer'],
    stage: 'MVP Stage',
    remote: true,
    likes: 0,
    shares: 0,
    noActions: true,
  },
  {
    id: 'kabir_onboarding',
    authorKey: 'kabir',
    tagType: 'idea',
    text: 'Prototyping a new onboarding flow for first-time founders.',
    meta: 'Founder · Foundators · 3d ago',
    cats: [],
    likes: 42,
    shares: 4,
  },
  {
    id: 'kabir_signups',
    authorKey: 'kabir',
    tagType: 'update',
    text: "Hit 500 signups this week 🎉 Thank you to everyone who's tried the beta.",
    meta: 'Founder · Foundators · 1w ago',
    cats: [],
    likes: 88,
    shares: 6,
    likedDefault: true,
    bookmarkedDefault: true,
  },
];

export const INITIAL_COMMENTS = {
  arjun_idea: [
    { who: 'meera', text: 'This is brilliant, would love to try it early.' },
    { who: 'ishita', text: 'The UX for adaptive difficulty is the hard part — happy to help think through it.' },
  ],
  meera_update: [
    { who: 'arjun', text: 'Huge! What was your biggest channel for the first 100?' },
    { who: 'rohan', text: 'Congrats Meera, following this closely.' },
  ],
  rohan_cofounder: [
    { who: 'daniel', text: "I'd love to chat — sent you a DM." },
  ],
  kabir_onboarding: [
    { who: 'meera', text: 'This is brilliant, would love to try it early.' },
    { who: 'arjun', text: 'Send me the Figma link when you can!' },
  ],
  kabir_signups: [
    { who: 'sophia', text: "Love this momentum — let's talk." },
  ],
};

export const INITIAL_DISCUSSIONS = {
  saas: {
    id: 'saas',
    title: 'Is AI making SaaS easier to build or harder to differentiate?',
    views: '1.2K',
    comments: [
      { who: 'meera', text: 'Easier to build, much harder to differentiate. Distribution is the new moat.' },
      { who: 'rohan', text: 'Agreed — the code is commoditized, trust and community are not.' },
    ],
  },
  users100: {
    id: 'users100',
    title: "What's the hardest part of finding your first 100 users?",
    views: '643',
    comments: [
      { who: 'arjun', text: 'Getting people to care before you have social proof. Cold outreach that actually works.' },
    ],
  },
};

export const INITIAL_CONTACTS = {
  sophia: {
    name: 'Sophia Turner',
    avatar: 'https://i.pravatar.cc/160?img=47',
    online: true,
    status: 'Online',
    lastActive: '10:24 AM',
    messages: [
      { who: 'in', text: 'Hey! 👋', time: '10:24 AM' },
      { who: 'in', text: 'I saw your project on Foundators...', time: '10:24 AM' },
      { who: 'out', text: 'Hey Sophia! Thanks for reaching out. 😊', time: '10:25 AM' },
      { who: 'out', text: "Yes, I'm really excited about it. Let's connect and discuss further.", time: '10:25 AM' },
      { who: 'in', text: "Great! I'll share more details in a bit.", time: '10:26 AM' },
      { who: 'file', name: 'Project_Overview.pdf', size: '1.2 MB', time: '10:27 AM' },
    ],
  },
  daniel: {
    name: 'Daniel Brooks',
    avatar: 'https://i.pravatar.cc/160?img=52',
    online: true,
    status: 'Online',
    lastActive: 'Yesterday',
    messages: [
      { who: 'in', text: 'Would love to collaborate on your idea.', time: 'Yesterday' },
    ],
  },
  emily: {
    name: 'Emily Carter',
    avatar: 'https://i.pravatar.cc/160?img=45',
    online: false,
    status: 'Offline',
    lastActive: 'Yesterday',
    messages: [
      { who: 'in', text: "Let's connect and build something amazing.", time: 'Yesterday' },
    ],
  },
  community: {
    name: 'Foundators Community',
    avatar: null,
    online: true,
    status: '128 members',
    lastActive: 'Mon',
    isGroup: true,
    messages: [
      { who: 'in', text: "Alex: Great insights from today's discussion!", time: 'Mon' },
    ],
  },
  james: {
    name: 'James Wilson',
    avatar: 'https://i.pravatar.cc/160?img=14',
    online: true,
    status: 'Online',
    lastActive: 'Sun',
    messages: [
      { who: 'in', text: 'Check out this resource, it might help.', time: 'Sun' },
    ],
  },
};

export const INITIAL_NOTIFICATIONS = [
  { id: 'n1', type: 'like', actorKey: 'arjun', text: 'liked your idea "College timetable AI assistant"', time: '5m ago', read: false, linkType: 'post', linkId: 'kabir_onboarding' },
  { id: 'n2', type: 'comment', actorKey: 'meera', text: 'commented: "This is brilliant, would love to try it early."', time: '32m ago', read: false, linkType: 'post', linkId: 'kabir_onboarding' },
  { id: 'n3', type: 'collab', actorKey: 'rohan', text: 'wants to collaborate on your post', time: '1h ago', read: false, linkType: 'user', linkId: 'rohan' },
  { id: 'n4', type: 'follow', actorKey: 'ishita', text: 'started following you', time: '2h ago', read: false, linkType: 'user', linkId: 'ishita' },
  { id: 'n5', type: 'comment', actorKey: null, text: 'Foundators Community — new reply in "Is AI making SaaS easier to build?"', time: 'Yesterday', read: true, linkType: 'discussion', linkId: 'saas' },
  { id: 'n6', type: 'update', actorKey: null, text: 'Payvance posted an update: "We crossed $1M ARR!"', time: '2 days ago', read: true, linkType: 'startup', linkId: 'payvance' },
  { id: 'n7', type: 'mention', actorKey: 'daniel', text: 'mentioned you in a comment', time: '3 days ago', read: true, linkType: 'user', linkId: 'daniel' },
];

export const GESTURE_TEMPLATES = [
  // ---------- Propose ----------
  {
    key: 'propose1',
    name: 'Heart Proposal',
    emoji: '💍',
    category: 'propose',
    description: 'A heartfelt proposal with a sparkling ring.',
    animation: 'glow',
  },
  {
    key: 'propose2',
    name: 'Rose Proposal',
    emoji: '🌹',
    category: 'propose',
    description: 'Romantic rose petal proposal.',
    animation: 'float',
  },
  {
    key: 'propose3',
    name: 'Proposal Box',
    emoji: '📦',
    category: 'propose',
    description: 'Ring box opening animation with a surprise ring inside.',
    animation: 'bounce',
  },
  {
    key: 'propose4',
    name: 'Will You?',
    emoji: '💖',
    category: 'propose',
    description: 'Shimmering text with a pulsing romantic glow.',
    animation: 'pulse',
  },
  {
    key: 'propose5',
    name: 'Forever',
    emoji: '♾️',
    category: 'propose',
    description: 'Infinity symbol animation representing eternal love.',
    animation: 'rotate',
  },

  // ---------- Sorry ----------
  {
    key: 'sorry1',
    name: 'Apology',
    emoji: '🙏',
    category: 'sorry',
    description: 'A sincere apology with folded hands.',
    animation: 'pulse',
  },
  {
    key: 'sorry2',
    name: 'Forgive Me',
    emoji: '🙇',
    category: 'sorry',
    description: 'Kneeling figure bowing in apology.',
    animation: 'bounce',
  },
  {
    key: 'sorry3',
    name: 'My Bad',
    emoji: '😅',
    category: 'sorry',
    description: 'Comic-style sorry text with a sheepish grin.',
    animation: 'shake',
  },
  {
    key: 'sorry4',
    name: 'Heart Repair',
    emoji: '💔',
    category: 'sorry',
    description: 'Broken heart slowly mending back together.',
    animation: 'pulse',
  },

  // ---------- Birthday ----------
  {
    key: 'birthday1',
    name: 'Birthday Cake',
    emoji: '🎂',
    category: 'birthday',
    description: 'A delicious cake with flickering candles.',
    animation: 'bounce',
  },
  {
    key: 'birthday2',
    name: 'Party Hat',
    emoji: '🎉',
    category: 'birthday',
    description: 'Festive party hat with confetti.',
    animation: 'float',
  },
  {
    key: 'birthday3',
    name: 'Balloon Pop',
    emoji: '🎈',
    category: 'birthday',
    description: 'Colorful balloons rising and gently popping.',
    animation: 'float',
  },
  {
    key: 'birthday4',
    name: 'Age Reveal',
    emoji: '🔢',
    category: 'birthday',
    description: 'Number counter animation revealing the age.',
    animation: 'bounce',
  },
  {
    key: 'birthday5',
    name: 'Cake Candles',
    emoji: '🕯️',
    category: 'birthday',
    description: 'Flickering candle flames on a birthday cake.',
    animation: 'glow',
  },
  {
    key: 'birthday6',
    name: 'Party Time',
    emoji: '🪩',
    category: 'birthday',
    description: 'Disco ball spinning with colorful party lights.',
    animation: 'rotate',
  },

  // ---------- Hi / Welcome ----------
  {
    key: 'hi1',
    name: 'Wave Hello',
    emoji: '👋',
    category: 'hi',
    description: 'A friendly wave to say hello.',
    animation: 'wave',
  },
  {
    key: 'hi2',
    name: 'High Five',
    emoji: '🖐️',
    category: 'hi',
    description: 'Enthusiastic high five greeting.',
    animation: 'bounce',
  },
  {
    key: 'hi3',
    name: 'Welcome Aboard',
    emoji: '🚢',
    category: 'hi',
    description: 'Ship sailing animation welcoming someone aboard.',
    animation: 'float',
  },
  {
    key: 'hi4',
    name: 'New Beginnings',
    emoji: '🌅',
    category: 'hi',
    description: 'Sunrise animation symbolizing a fresh start.',
    animation: 'glow',
  },
  {
    key: 'hi5',
    name: 'Hello There',
    emoji: '🫵',
    category: 'hi',
    description: 'Waving hand animation with a cheerful hello.',
    animation: 'wave',
  },

  // ---------- Thank You ----------
  {
    key: 'thankyou1',
    name: 'Thank You',
    emoji: '🙏',
    category: 'thankyou',
    description: 'Heartfelt thanks with grateful hands.',
    animation: 'pulse',
  },
  {
    key: 'thankyou2',
    name: 'Grateful Heart',
    emoji: '❤️',
    category: 'thankyou',
    description: 'Heart beating animation expressing deep gratitude.',
    animation: 'pulse',
  },
  {
    key: 'thankyou3',
    name: "You're the Best",
    emoji: '🏆',
    category: 'thankyou',
    description: 'Trophy and medal animation celebrating someone.',
    animation: 'bounce',
  },
  {
    key: 'thankyou4',
    name: 'Many Thanks',
    emoji: '🌸',
    category: 'thankyou',
    description: 'Falling flowers showering thanks.',
    animation: 'float',
  },

  // ---------- Miss You ----------
  {
    key: 'missyou1',
    name: 'Missing You',
    emoji: '🥺',
    category: 'missyou',
    description: 'Sad eyes missing someone special.',
    animation: 'pulse',
  },
  {
    key: 'missyou2',
    name: 'Counting Stars',
    emoji: '⭐',
    category: 'missyou',
    description: 'Starfield animation with wishes on every star.',
    animation: 'glow',
  },
  {
    key: 'missyou3',
    name: 'Come Back Soon',
    emoji: '📅',
    category: 'missyou',
    description: 'Calendar pages flipping marking days apart.',
    animation: 'flip',
  },

  // ---------- Congrats ----------
  {
    key: 'congrats1',
    name: 'Congratulations',
    emoji: '🎊',
    category: 'congrats',
    description: 'Confetti celebration for a big achievement.',
    animation: 'explode',
  },
  {
    key: 'congrats2',
    name: 'Champion',
    emoji: '🥇',
    category: 'congrats',
    description: 'Gold medal award ceremony animation.',
    animation: 'bounce',
  },
  {
    key: 'congrats3',
    name: 'Level Up',
    emoji: '📈',
    category: 'congrats',
    description: 'Progress bar filling to celebrate leveling up.',
    animation: 'fill',
  },
];

export function getPerson(key) {
  if (key === 'kabir') return KABIR;
  return USERS[key] || null;
}

// ---------------------------------------------------------------------------
// FOUNDATORS MATCH — the "What are you building today?" intent engine
// ---------------------------------------------------------------------------
// Real matching in a production version of this would run against a live
// database and a real ranking model. Here, match scores are computed live
// from actual shared-skill overlap (not random) — honest about being a
// prototype heuristic, not a trained ML model.

export const INTENTS = [
  { key: 'start_business', label: 'Start a business', emoji: '💡', mode: 'team' },
  { key: 'find_programmer', label: 'Find a programmer', emoji: '👨‍💻', mode: 'people', skills: ['Development', 'AI', 'SaaS'] },
  { key: 'find_cofounder', label: 'Find a co-founder', emoji: '🤝', mode: 'people', skills: ['Startups', 'Product', 'Operations'] },
  { key: 'find_job', label: 'Find a job', emoji: '💼', mode: 'opportunities', oppType: 'job' },
  { key: 'find_funding', label: 'Find funding', emoji: '💰', mode: 'opportunities', oppType: 'funding' },
  { key: 'learn_skill', label: 'Learn a skill', emoji: '🎓', mode: 'people', skills: ['Design', 'Development', 'Marketing', 'AI'] },
  { key: 'find_mentor', label: 'Find a mentor', emoji: '🧑‍🏫', mode: 'people', skills: ['Investing', 'Strategy', 'Operations'] },
  { key: 'join_project', label: 'Join a project', emoji: '🚀', mode: 'opportunities', oppType: 'project' },
  { key: 'hire_someone', label: 'Hire someone', emoji: '🛠️', mode: 'people', skills: ['Development', 'Design', 'Marketing'] },
  { key: 'network_locally', label: 'Network locally', emoji: '🌎', mode: 'local' },
];
